name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install latest Rust stable
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-gnu

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile'

    # - name: Get test coverage
    #   id: coverage
    #   uses: actions-rs/grcov@v0.1

    # - name: Coveralls upload
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: ${{ steps.coverage.outputs.report }}
